name = "ticket-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "533d313ef170042c947d37bf2ab123b8"
workers_dev = false

# Custom Domain
routes = [
	{ pattern = "tickets.blindsoft.net", custom_domain = true }
]

[[kv_namespaces]]
binding = "TICKET_DB"
id = "628c6e2c13a64ef89170df5679b87b00"

[ai]
binding = "AI"
